In [ ]:
#Alexix Velasquez #Swati
#https://www.kaggle.com/datasets/vijayashreer/food-preferences

In [ ]:
#import library needed to run categorical NB
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
#Load the dataset
df = pd.read_csv("food_preference.csv")

In [ ]:
#Display the data set to see what columns we are working with
df

,Timestamp,Participant_ID,Gender,Nationality,Age,Food,Juice,Dessert
0,2019/05/07 2:59:13 PM GMT+8,FPS001,Male,Indian,24,Traditional food,Fresh Juice,Maybe
1,2019/05/07 2:59:45 PM GMT+8,FPS002,Female,Indian,22,Western Food,Carbonated drinks,Yes
2,2019/05/07 3:00:05 PM GMT+8,FPS003,Male,Indian,31,Western Food,Fresh Juice,Maybe
3,2019/05/07 3:00:11 PM GMT+8,FPS004,Female,Indian,25,Traditional food,Fresh Juice,Maybe
4,2019/05/07 3:02:50 PM GMT+8,FPS005,Male,Indian,27,Traditional food,Fresh Juice,Maybe
...,...,...,...,...,...,...,...,...
283,2019/05/10 9:24:00 AM GMT+8,FPS284,Male,Indian,27,Western Food,Fresh Juice,Yes
284,2019/05/10 9:32:54 AM GMT+8,FPS285,Male,Indian,24,Traditional food,Fresh Juice,Yes
285,2019/05/10 12:09:17 PM GMT+8,FPS286,Male,Indian,25,Traditional food,Fresh Juice,Yes
286,2019/05/10 12:52:17 PM GMT+8,FPS287,Male,Indian,27,Traditional food,Fresh Juice,Yes
287,2019/05/10 12:55:42 PM GMT+8,FPS288,Male,Indian,27,Traditional food,Fresh Juice,No

In [ ]:
#Dropped Timestamp, participant id, and age since they aren't needed for the prediction
df.drop(["Timestamp","Participant_ID","Age"], axis=1, inplace=True)
df

     Gender Nationality              Food              Juice Dessert
0      Male      Indian  Traditional food        Fresh Juice   Maybe
1    Female      Indian      Western Food  Carbonated drinks     Yes
2      Male      Indian      Western Food        Fresh Juice   Maybe
3    Female      Indian  Traditional food        Fresh Juice   Maybe
4      Male      Indian  Traditional food        Fresh Juice   Maybe
..      ...         ...               ...                ...     ...
283    Male      Indian      Western Food        Fresh Juice     Yes
284    Male      Indian  Traditional food        Fresh Juice     Yes
285    Male      Indian  Traditional food        Fresh Juice     Yes
286    Male      Indian  Traditional food        Fresh Juice     Yes
287    Male      Indian  Traditional food        Fresh Juice      No

[288 rows x 5 columns]

In [ ]:
#Check for missing values in each column
print(df.isnull().sum())

Gender         4
Nationality    0
Food           0
Juice          0
Dessert        0
dtype: int64

In [ ]:
#Drop the missing values
#Display the cleaned dataset
df.dropna(inplace=True)
df

     Gender Nationality              Food              Juice Dessert
0      Male      Indian  Traditional food        Fresh Juice   Maybe
1    Female      Indian      Western Food  Carbonated drinks     Yes
2      Male      Indian      Western Food        Fresh Juice   Maybe
3    Female      Indian  Traditional food        Fresh Juice   Maybe
4      Male      Indian  Traditional food        Fresh Juice   Maybe
..      ...         ...               ...                ...     ...
283    Male      Indian      Western Food        Fresh Juice     Yes
284    Male      Indian  Traditional food        Fresh Juice     Yes
285    Male      Indian  Traditional food        Fresh Juice     Yes
286    Male      Indian  Traditional food        Fresh Juice     Yes
287    Male      Indian  Traditional food        Fresh Juice      No

[284 rows x 5 columns]

In [ ]:
#Verify all missing values are removed
print(df.isnull().sum())

Gender         0
Nationality    0
Food           0
Juice          0
Dessert        0
dtype: int64

In [ ]:
#Create LabelEncoders to convert categorical values into numbers
#Each column needs its own encoder
encoder_gender = LabelEncoder()
encoder_nationality = LabelEncoder()
encoder_food = LabelEncoder()
encoder_juice = LabelEncoder()
encoder_target = LabelEncoder()

#Convert each column from words to numbers
df["Gender_num"] = encoder_gender.fit_transform(df["Gender"])
df["Nationality_num"] = encoder_nationality.fit_transform(df["Nationality"])
df["Food_num"] = encoder_food.fit_transform(df["Food"])
df["Juice_num"] = encoder_juice.fit_transform(df["Juice"])
df["Dessert_num"] = encoder_target.fit_transform(df["Dessert"])

print(df[["Gender", "Gender_num", "Nationality","Nationality_num","Food", "Food_num","Juice", "Juice_num","Dessert","Dessert_num"
]])
print()

     Gender  Gender_num Nationality  Nationality_num              Food  \
0      Male           1      Indian                3  Traditional food
1    Female           0      Indian                3      Western Food
2      Male           1      Indian                3      Western Food
3    Female           0      Indian                3  Traditional food
4      Male           1      Indian                3  Traditional food
..      ...         ...         ...              ...               ...
283    Male           1      Indian                3      Western Food
284    Male           1      Indian                3  Traditional food
285    Male           1      Indian                3  Traditional food
286    Male           1      Indian                3  Traditional food
287    Male           1      Indian                3  Traditional food

     Food_num              Juice  Juice_num Dessert  Dessert_num
0           0        Fresh Juice          1   Maybe            0
1           1  Carbonated drinks          0     Yes            2
2           1        Fresh Juice          1   Maybe            0
3           0        Fresh Juice          1   Maybe            0
4           0        Fresh Juice          1   Maybe            0
..        ...                ...        ...     ...          ...
283         1        Fresh Juice          1     Yes            2
284         0        Fresh Juice          1     Yes            2
285         0        Fresh Juice          1     Yes            2
286         0        Fresh Juice          1     Yes            2
287         0        Fresh Juice          1      No            1

[284 rows x 10 columns]

In [ ]:
#Define features (X) and target (y)
#X is used to make predictions
#y what we are trying to predict
X = df[["Gender_num", "Nationality_num", "Food_num", "Juice_num"]]
y = df["Dessert_num"]

In [ ]:
#Create and train the Categorical Naive Bayes model
model = CategoricalNB()
model.fit(X, y)

CategoricalNB()

In [ ]:
#Here we create a new sample to test the model
#This is Data the model has never seen before
new_data = [["Male", "Indian", "Western Food", "Fresh Juice"]]

#Convert the new data using the same encoders used for training
#Here we use transform so we don't relearn categories
new_input = [[
    encoder_gender.transform([new_data[0][0]])[0],
    encoder_nationality.transform([new_data[0][1]])[0],
    encoder_food.transform([new_data[0][2]])[0],
    encoder_juice.transform([new_data[0][3]])[0]
]]

#Make prediction using the trained model
prediction = model.predict(new_input)[0]

#Get the probability of each possible outcome
probabilities = model.predict_proba(new_input)[0]

#Convert numeric prediction back to original label
result = encoder_target.inverse_transform([prediction])[0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

In [ ]:
#Here we display the prediction which was a Yes to dessert.
print("Prediction:", result)
print("Porbabilities:", probabilities)

Prediction: Yes
Porbabilities: [0.42457974 0.05933137 0.51608888]

The categoricalNB model uses categorical data like gender, nationality, food, and juice to predict a person's dessert preference. The dataset was cleaned by removing unnecessary columns and dropping rows with missing values to make sure the model runs properly. Then we converted the categorical values into numbers using labelencoder so the model can process them. After that the data was split into features (X) and the target (y), and a categorical naive bayes model was trained. Lastly we added a new sample to test the model and it returned a prediction and probabilities for each outcome. This model shows using probability to make a decision based on categorical inputs.